Show view
emmanuelsteven/MyBlogApp pull request #6
Opened 2023-08-30 08:46 UTC by emmanuelsteven

In this PR,
- I implemented the design from the sneak peek wireframes.

2023-08-30 10:19 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @emmanuelsteven 

Good job so far 👏! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Descriptive PR and README file
- ✅ Correct Linters

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

- [OPTIONAL] Kindly make sure to use descriptive commit messages - each commit is small enough to describe it in one sentence. Also, please ensure that the commit message is written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8).

  Here are some examples of descriptive commits
  ![image](https://github.com/emmanuelsteven/MyBlogApp/assets/106119105/bf838ff4-59f1-4ca1-bd2b-2db70fd9ae28)



_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 10:19 UTC, KanzaTahreem commented on app/controllers/users_controller.rb
> +  end
**_I really appreciate your efforts for defining all actions 👏👏 I noticed that the PR includes a code that is out of the scope of the current project and it is not going to be reviewed 📁Please remember to provide a link to the additional code in the Pull Request created for the next project. For example: you can create a link(s) to specific commit(s) and/or line(s) of code in the Pull Request for current milestone and include that link in the description of Pull Request for your next milestone. Similarly for the `posts_controller`_**

2023-08-30 10:19 UTC, KanzaTahreem commented on app/views/users/index.html.erb
> +   <%end%>
- [ ] Great work so far! 👏 However, that's how an image is being displayed on the screen with a valid image URL 👇Kindly make sure to fix this wherever an image is used.

![localhost_3000_users_](https://github.com/emmanuelsteven/MyBlogApp/assets/106119105/135a2049-2c72-4702-bd4e-aa6810c351bb)

2023-08-30 10:19 UTC, KanzaTahreem commented on app/views/posts/index.html.erb
> +  <% comments.each do |comment|%>
- [ ] Great job on your progress! 👏 I encountered the following error when clicking on the "See all posts" button/link ⚠. Please resolve this issue. Additionally, please ensure that you render the five most recent comments on the `app/views/posts/index.html.erb` page using the method defined in the model. 💪


![image](https://github.com/emmanuelsteven/MyBlogApp/assets/106119105/2aad70ea-16e9-4e76-92b2-54f615ceb22d)

2023-08-30 10:19 UTC, KanzaTahreem commented on app/views/posts/show.html.erb
> +</article>
- [ ] Kindly make sure to follow the given wireframe for styling the posts's show page. It's nice to have styling, however, please make sure that general layout remains the same. Kindly have a look at the following comparison for better clarity 💡👇


**_Current implementation_**
![localhost_3000_users_1_posts_2](https://github.com/emmanuelsteven/MyBlogApp/assets/106119105/cf603f07-1a41-4751-a03a-e1ffc90e4713) 

**_Given wireframe_**
![image](https://github.com/emmanuelsteven/MyBlogApp/assets/106119105/2959fe8a-e833-4f72-8ac6-aaececc7d4e5)

2023-08-31 01:03 UTC, jerryowusu requested changes
Hi @emmanuelsteven 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close](https://github.com/emmanuelsteven/MyBlogApp/assets/65233860/01eef421-debd-4ebe-9d7c-08002f014d88)


 ## Highlights
Nice design :+1: 
Added seed data :100: 
Neat code :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 01:03 UTC, jerryowusu commented on app/views/users/index.html.erb
> + <div class='user-content2'>
As requested by the previous reviewer, you need to restrict your images from filling the whole page. Some images fit perfectly whiles some stretch to fill the whole page as shown below. Kindly add the width and height to your images  to prevent them from oversizing :wink: 

![Screenshot from 2023-08-31 00-48-40](https://github.com/emmanuelsteven/MyBlogApp/assets/65233860/be407e76-174c-4865-a497-a4fa6a0dfca2)

![Screenshot from 2023-08-31 00-49-25](https://github.com/emmanuelsteven/MyBlogApp/assets/65233860/c9807809-4e4a-4f75-bec3-32432076bf1f)

2023-08-31 01:03 UTC, jerryowusu commented on app/views/posts/show.html.erb
> +</article>
Nice effort for making the requested changes. However, kindly check the border in the posts show page. The first box/border contains the post title, comments and likes as well as the message/post body. Please update it to match the given wireframe as shown below. 

### Your design 

![Screenshot from 2023-08-31 00-58-31](https://github.com/emmanuelsteven/MyBlogApp/assets/65233860/f42cb5c4-c184-44dc-8ef2-55a2629201d5)


### Actual design 

![Screenshot from 2023-08-31 01-00-56](https://github.com/emmanuelsteven/MyBlogApp/assets/65233860/39711565-f91c-43fc-9d6b-f72f188f69c1)

2023-08-31 10:04 UTC, prolajumokeoni approved these changes
Hi @emmanuelsteven 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Images and border added  ✅ 
   

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 10:05 UTC, merged